-- CreateEnum
CREATE TYPE "DriverStatus" AS ENUM ('PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "BusType" AS ENUM ('TSRTC_CITY_ORDINARY', 'TSRTC_METRO_EXPRESS', 'TSRTC_METRO_DELUXE', 'TSRTC_SUPER_LUXURY', 'TSRTC_GARUDA_PLUS', 'TSRTC_RAJDHANI', 'TSRTC_PALLE_VELUGU', 'TSRTC_EXPRESS', 'TSRTC_ELECTRIC_AC');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "busType" "BusType",
ADD COLUMN     "city" VARCHAR(128),
ADD COLUMN     "depotLocation" VARCHAR(256),
ADD COLUMN     "driverStatus" "DriverStatus",
ADD COLUMN     "experience" INTEGER,
ADD COLUMN     "licenseNumber" VARCHAR(64);
